on:
  push:
    branches:
      - main
jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: '3.2.8-spacy-de'
         # requirements_file: requirements.txt
          data_validate: true
          rasa_train: true
          fine_tune: false
          cross_validation: false
          rasa_test: true
          test_type: all
          publish_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload model
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: gh-latest.tar.gz
          path: models
